---
title: Python库安装
date: 2016-11-08
tags:
- python
---



# Python库安装

pip 一键安装库

```python
pip3 install requests bs4 pymongo mongoengine jupy
```

Ubuntu16.04问题

```shell
root@centos-512mb-nyc3-01:~# pip3 list
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

# 换个命令试试
root@centos-512mb-nyc3-01:~# python3 -m pip list
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 19, in <module>
    sys.exit(pip.main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

# 解决
export LC_ALL=C
```

Python的在线编译器

jupyter notebook命令会默认开启8888端口，会和surge起冲突

解决：

```shell
jupyter notebook --port [自定义端口]
```



